kind=defined
names=assert_operator
visibility=public

--- assert_operator(object1, operator, object2, message="")    -> ()

object1.send(operator, object2) が真ならパスします。

@raise Test::Unit::AssertionFailedError assert が失敗した時に発生します。


